### ISSUE TITLE
Android 7.0 support please

### ISSUE THREAD

**Issue by webiummedia** [amartinz/AndroidSurveilance#1]
I know this project is unsupported now but I am very interested in it and was wandering if you would be interested to make it support all up to android 7.0 and add a few more features. I can even give you some cash for this. Please contact me on skype. web2c.psimard. Tell me your from AndroidSurveilance in your skype request of I might not accept your request lol.

**Comment by amartinz** [comment]
I only develop such kind of applications for serious companies anymore, due many people misusing surveilance apps for malicious reasons.

This will cost you plenty of money and according to how you contact me and the quality of the proposal, i have to decline.

Have a nice day!
